version: "3.6"
services:

  nginx:
    build: nginx/
    ports:
      - "8080:80"
    links:
      - php

  php:
    build: php/
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
    volumes:
      - ./php:/src
